development:
  adapter: postgresql
  encoding: unicode
  database: skeleton_development
  username: postgres

test:
  adapter: postgresql
  encoding: unicode
  database: skeleton_test
  username: postgres

production:
  adapter: postgresql
  encoding: unicode
  database: skeleton_production
  pool: 5
  username: skeleton
  password:
